name: Windows vcpkg CGAL Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_INSTALLATION_ROOT: C:\vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: C:\vcpkg\vcpkg_cache

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache vcpkg binaries
      uses: actions/cache@v3
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Configure CMake
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_INSTALLATION_ROOT }}\scripts\buildsystems\vcpkg.cmake"

    - name: Build project
      run: cmake --build build --config Release
