name: Windows vcpkg CGAL Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}\vcpkg_cache

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache vcpkg binaries
      uses: actions/cache@v3
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Install dependencies (manifest mode)
      run: |
        vcpkg install --triplet x64-windows --binarysource=clear;files,${{ env.VCPKG_DEFAULT_BINARY_CACHE }},readwrite
